name: build cli for all platforms

on:
  push:
    tags:
      - '*'
#on:
#  push:
#    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]
#permissions:
#  contents: write

jobs:
  make-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
  build-all-for-all:
    runs-on: ubuntu-latest
    needs:
      - make-release
    strategy:
      matrix:
        goos: [linux, freebsd, darwin, windows]
        goarch: [amd64, arm64, riscv64]
        exclude:
          - goarch: arm64
            goos: windows
          - goarch: riscv64
            goos: windows
          - goarch: riscv64
            goos: darwin
          - goarch: arm64
            goos: freebsd
    steps:
      - uses: actions/checkout@v3
      - uses: wangyoucao577/go-release-action@v1.40
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          ldflags: -X main.version=${{ github.ref_name }}
          overwrite: true
          md5sum: false
          sha256sum: false
          compress_assets: false
          project_path: './src'
          #build_command: go build -o nostr-post-${{ github.ref_name }} src/main.go
          #build_command: go build -o nostr-post-0.0.5-linux-arm64 src/main.go
         # build_command: make clean && make build
